#!/usr/bin/env python3
"""
build.py: builds the Clinical Supplement Suite (tools.neurominds.uk).

Usage:
    py build.py

Output:
    public/index.html   (committed; Cloudflare Pages serves public/ as-is, no build step)

The instrument engine (registry, scoring, norms, results, runner) is NOT copied
into this repo. It lives in the Neurominds assessment app, which stays the single
source of truth, so a verification fix made there reaches this tool on the next
rebuild here. This script only READS the app's files and never writes to the app
repo, so building here cannot affect the app.

Where the app lives: ../assessment_suite_project by default, or set
SUPPLEMENT_APP_DIR to point elsewhere.
"""

import os, re, base64, json, mimetypes, subprocess, sys
from pathlib import Path

HERE = Path(__file__).parent
APP_REPO = Path(os.environ.get('SUPPLEMENT_APP_DIR') or (HERE.parent / 'assessment_suite_project')).resolve()
SRC = APP_REPO / 'assessment_suite'
OUT = HERE / 'public' / 'index.html'

if not (SRC / 'engine' / 'registry.js').is_file():
    sys.exit(f"[ABORT] App source not found at {SRC}. Set SUPPLEMENT_APP_DIR to the app repo.")

# Which app commit this build came from, so what's live is always traceable.
def _git(*args):
    r = subprocess.run(['git', '-C', str(APP_REPO), *args], capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else ''
app_commit = _git('rev-parse', '--short', 'HEAD') or 'unknown'
app_dirty = bool(_git('status', '--porcelain', '--', 'assessment_suite', 'norms', 'scripts/validate.cjs'))
print(f"App source: {SRC}")
print(f"App commit: {app_commit}{' (with uncommitted changes)' if app_dirty else ''}")

# ── Integrity gate ───────────────────────────────────────────────────────────────
# The app's own validator (read-only). Corrupted clinical data never ships.
print("Validating registry / norms ...")
_validator = APP_REPO / 'scripts' / 'validate.cjs'
try:
    _vres = subprocess.run(['node', str(_validator)], capture_output=True, text=True)
except FileNotFoundError:
    sys.exit("[ABORT] Node.js not found on PATH; required to run the build-time validator.")
print((_vres.stdout or '').strip())
if _vres.returncode != 0:
    if (_vres.stderr or '').strip():
        print(_vres.stderr.strip())
    sys.exit("[ABORT] validateRegistry found errors; build stopped. Fix the data in the app and re-run.")


# ── Cut-off master (generated in memory from the app's norms/cutoffs.csv) ────────
# The app's build writes this to engine/cutoffs_master.js; here it is built in
# memory instead so nothing in the app repo is ever written.
def build_cutoffs_master():
    import csv
    src = APP_REPO / 'norms' / 'cutoffs.csv'
    with open(src, encoding='utf-8', newline='') as f:
        rows = list(csv.DictReader(f))
    keep = ['instrument', 'instrument_name', 'scale', 'cutoff', 'label', 'recommended',
            'sensitivity', 'specificity', 'target', 'comparison', 'reference_standard',
            'n_cases', 'n_noncases', 'setting', 'figure_type', 'source', 'verified']
    out = []
    for i, r in enumerate(rows, start=2):
        if None in r or any(r.get(k) is None for k in keep):
            sys.exit(f"[ABORT] norms/cutoffs.csv line {i} has the wrong number of columns "
                     "(an unquoted comma?). Fix the row in the app and re-run.")
        if r['instrument'].strip() not in set(ALLOW):
            continue   # excluded instruments: no statistics in the hosted file either
        if (r['sensitivity'] or '').strip() or (r['specificity'] or '').strip():
            out.append({k: (r[k] or '').strip() for k in keep})
    print(f"[OK] cut-off master: {len(out)} cut-off rows with sensitivity/specificity")
    return ("/* GENERATED by build.py from norms/cutoffs.csv. Do not edit; edit the CSV. */\n"
            "window.CUTOFFS_MASTER = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n")

def build_image_map():
    """Inline every RMET eye photo as a base64 data URI so the single file works
    on its own."""
    img_dir = SRC / 'assets' / 'rmet-images'
    if not img_dir.is_dir():
        return ''
    images = {}
    for p in sorted(img_dir.glob('image-*.jpg')):
        mime = mimetypes.guess_type(p.name)[0] or 'image/jpeg'
        b64 = base64.b64encode(p.read_bytes()).decode('ascii')
        images[p.name] = f'data:{mime};base64,{b64}'
    if not images:
        return ''
    print(f"  Inlined {len(images)} RMET image(s)")
    return 'window.RMET_IMAGES = ' + json.dumps(images) + ';\n'

# Load source files in dependency order (UTF-8: sources contain curly quotes etc.)
css     = (SRC / 'ui/styles.css').read_text(encoding='utf-8')
def _inline_font(m):
    fp = SRC / 'assets/fonts' / m.group(1)
    return 'url("data:font/woff2;base64,' + base64.b64encode(fp.read_bytes()).decode('ascii') + '")'
css, n_fonts = re.subn(r'url\("\.\./assets/fonts/([\w.-]+\.woff2)"\)', _inline_font, css)
print(f"  Inlined {n_fonts} font file(s)")
config  = (SRC / 'engine/config.js').read_text(encoding='utf-8')
scoring = (SRC / 'engine/scoring.js').read_text(encoding='utf-8')
sdqnorms= (SRC / 'engine/sdq_norms.js').read_text(encoding='utf-8')
scrnorms= (SRC / 'engine/screener_norms.js').read_text(encoding='utf-8')
registry= (SRC / 'engine/registry.js').read_text(encoding='utf-8')
validate= (SRC / 'engine/validate.js').read_text(encoding='utf-8')
state   = (SRC / 'engine/state.js').read_text(encoding='utf-8')
app     = (SRC / 'ui/app.js').read_text(encoding='utf-8')
results = (SRC / 'ui/results.js').read_text(encoding='utf-8')
shell   = (SRC / 'index.html').read_text(encoding='utf-8')

# The session interface (this repo's own files, layered on the app's engine:
# it calls REGISTRY, Scoring.run and App.resultBody, never copies them).
suite_css = (HERE / 'ui' / 'suite.css').read_text(encoding='utf-8')
suite_js  = (HERE / 'ui' / 'suite.js').read_text(encoding='utf-8')

# Force local mode no matter where the file is hosted (auto-detect would flip to
# 'online' on a web host), and strip the Supabase credentials: this tool never
# talks to the app's backend.
config, n_mode = re.subn(r"mode:\s*'auto'", "mode: 'local'", config, count=1)
if n_mode != 1:
    raise ValueError("config.js: expected exactly one mode:'auto' to force to 'local'")
config = re.sub(r"(supabaseUrl:\s*)'[^']*'", r"\1''", config)
config = re.sub(r"(supabaseAnonKey:\s*)'[^']*'", r"\1''", config)

def strip_file_header(js):
    m = re.match(r'/\*.*?\*/[ \t]*\r?\n(?:[ \t]*\r?\n)*', js, re.DOTALL)
    return js[m.end():] if m else js

image_map = build_image_map()

body_match = re.search(r'<body>(.*?)</body>', shell, re.DOTALL)
if not body_match:
    raise ValueError("Could not find <body> in index.html")
body = body_match.group(1)
body = re.sub(r'\n<script src=[^>]+></script>', '', body)
body = re.sub(r'\n<script>\s*/\* Boot \*/.*?</script>\n', '', body, flags=re.DOTALL)
body = body.strip()


# ── Copyright filter ─────────────────────────────────────────────────────────────
# A publicly hosted clinician tool, so the library is filtered to a copyright-clean
# ALLOW list at boot, and the licensed clinician interview modules (DIVA/DASI/
# ADI-R/ADOS) are never bundled. Excluded on purpose: baars_self/baars_informant
# (proprietary, Guilford), diva, young_diva, dasi, adir, adirw, ados_m4 (licensed/
# training-gated), rcads x4 (permission covers the clinic EHR only), iesr and the
# Y-BOCS family (rights holders forbid web posting outright, see the strip step
# below). To change the visible set, edit ALLOW below; nothing else needs to move.
#
# ALLOW hides a card; it does NOT remove its item text from the file. Anything
# excluded for COPYRIGHT (rather than for licence-gating or training) must also be
# stripped below. Keep the two lists in step when adding an instrument.
ALLOW = [
    # autism / social
    'aq_adult', 'aq_adolescent', 'aq_child', 'rmet', 'cati', 'catq', 'gsq', 'sqa2', 'coventry',
    'rbq3_self', 'rbq3_other',
    # sensory (gsq_p: offered free by the authors, Smees et al. 2022, CC-BY)
    'gsq_p', 'rgsq_p', 'spq', 'spq35',
    # adhd
    'asrs', 'asrs_adolescent', 'asrs_observer', 'vand_parent', 'vand_teacher',
    'snap_parent', 'snap_teacher', 'wfirs_s', 'wfirs_p', 'wurs_self', 'wurs_observer',
    # mood / anxiety / other
    'phq9', 'gad7', 'lsas', 'assist', 'sad_child',
    # ocd. The Y-BOCS family is stripped outright (rights holder forbids web
    # posting), so the OCI pair is this build's only OCD coverage.
    # NOTE both are a documented RISK ACCEPTANCE, not a located licence. The
    # OCI-R is © Edna B. Foa 2002; the OCI-CV-R was published by Elsevier and
    # our copy is an NIHPA author manuscript, which grants no redistribution
    # right over the instrument itself. No grant permitting web publication was
    # found for either (see their `licence` fields in registry.js). Included by
    # Ryan's explicit decision, 2026-08-04. Remove these to reverse it.
    'ocir', 'oci_cv_r',
    # sleep (SCI-08: CC BY-NC 3.0 with the paper, Espie et al. 2014)
    'sci',
    # behaviour / development (informant)
    'sdq_parent', 'sdq_self',
]
_allow_js = json.dumps(ALLOW)
online_boot = f"""/* ── Boot (hosted, copyright-filtered) ─────────────────────────────────────── */
document.addEventListener('DOMContentLoaded', () => {{
  var ALLOW = new Set({_allow_js});
  Object.keys(REGISTRY).forEach(function(k){{ if(!ALLOW.has(k)) delete REGISTRY[k]; }});
  if (typeof CONFIG !== 'undefined' && Array.isArray(CONFIG.batteries)) {{
    CONFIG.batteries = CONFIG.batteries
      .map(function(b){{ return Object.assign({{}}, b, {{ tests: (b.tests||[]).filter(function(t){{ return ALLOW.has(t); }}) }}); }})
      .filter(function(b){{ return b.tests.length; }});
  }}
  Suite.boot();
}});"""

cutmaster = build_cutoffs_master()   # after ALLOW: filters the cut-off rows to the visible instruments

# registry.js carries protected item text for excluded instruments: the four
# proprietary BAARS-IV item arrays and the four RCADS arrays (47 + 25 item, self +
# parent; clinic EHR permission only). Empty them so the hosted file contains none
# of that content. (DIVA/DASI/ADI-R/ADOS live in engine files this build never
# bundles; the RCADS T-score tables live in rcads_norms.js / rcads25_norms.js,
# also never bundled here.)
registry_online, n_baars = re.subn(
    r"const (BAARS_SELF_CURRENT|BAARS_SELF_CHILD|BAARS_INF_CURRENT|BAARS_INF_CHILD) = \[.*?\n\];",
    r"const \1 = [];",
    registry, flags=re.DOTALL)
if n_baars != 4:
    raise ValueError(f"Expected to strip 4 BAARS item arrays, stripped {n_baars}; registry.js format changed.")
registry_online, n_rcads = re.subn(
    r"const (RCADS_ITEMS_SELF|RCADS_ITEMS_PARENT|RCADS25_ITEMS_SELF|RCADS25_ITEMS_PARENT) = \[.*?\n\];",
    r"const \1 = [];",
    registry_online, flags=re.DOTALL)
if n_rcads != 4:
    raise ValueError(f"Expected to strip 4 RCADS item arrays (47 + 25), stripped {n_rcads}; registry.js format changed.")

# IES-R and the Y-BOCS family: rights holders forbid web publication of the
# instrument itself, so the whole REGISTRY block is removed (emptying an item
# array would still leave the per-item response anchors).
#   IES-R      Weiss (2007), Guilford Press chapter.
#   Y-BOCS/CY-BOCS/self-report  OCD Scales, LLC (© Wayne K. Goodman); posting
#              on a website is not permissible without a licence agreement.
# Both stay available in the clinic's own app; this only governs public hosting.
registry_online, n_iesr = re.subn(
    r'Object\.assign\(REGISTRY, \{"iesr":\{.*?\n\}\}\);\n',
    '/* IES-R omitted from the hosted build (copyright: Weiss / Guilford Press). */\n',
    registry_online, flags=re.DOTALL)
if n_iesr != 1:
    raise ValueError(f"Expected to strip 1 IES-R registry block, stripped {n_iesr}; registry.js format changed.")
registry_online, n_ybocs = re.subn(
    r'/\* ── Y-BOCS — Yale-Brown Obsessive-Compulsive Scale.*?\n\}\)\(\);\n',
    '/* Y-BOCS family omitted from the hosted build (copyright: OCD Scales, LLC). */\n',
    registry_online, flags=re.DOTALL)
if n_ybocs != 1:
    raise ValueError(f"Expected to strip 1 Y-BOCS registry block, stripped {n_ybocs}; registry.js format changed.")

# The other excluded instruments (BAARS-IV, RCADS, RCADS-25, DIVA-5, Young DIVA-5,
# DASI-2, ADI-R, ADOS-2) are hidden at boot, but their registry blocks still carried
# names, citations and descriptions into the page source. Remove each block with
# its header comment, so nothing about them ships (audit 2026-10-02, issue 12).
_EXCL_BLOCKS = ['BAARS-IV', 'RCADS — ', 'RCADS-25', 'DIVA-5 — ', 'Young DIVA-5', 'DASI-2',
                'ADI-R algorithm', 'ADI-R interview workspace', 'ADOS-2 Module 4']
for _hdr in _EXCL_BLOCKS:
    registry_online, _n = re.subn(
        r'/\* ── ' + re.escape(_hdr) + r'.*?Object\.assign\(REGISTRY, \{"[a-z0-9_]+":\{.*?\n\}\}\);\n',
        '/* (excluded instrument omitted from the hosted build) */\n',
        registry_online, count=1, flags=re.DOTALL)
    if _n != 1:
        raise ValueError(f"Expected to strip the '{_hdr}' registry block, stripped {_n}; registry.js format changed.")

# Their AGE_BOUNDS entries in state.js carry citation notes too (e.g. "Barkley
# 2011"); drop those lines so the excluded instruments leave no trace.
_EXCL_AGE = ['baars_self', 'baars_informant', 'rcads_self', 'rcads_parent', 'rcads25_self',
             'rcads25_parent', 'iesr', 'ybocs_clin', 'ybocs_sr', 'ybocs_check', 'ybocs_child',
             'ybocs_child_check']
state, _n_age = re.subn(r'(?m)^[ \t]*(' + '|'.join(_EXCL_AGE) + r'):[ \t]*\{.*\},?[ \t]*\r?\n', '', state)
if _n_age != len(_EXCL_AGE):
    raise ValueError(f"Expected to strip {len(_EXCL_AGE)} AGE_BOUNDS lines, stripped {_n_age}; state.js format changed.")

# Belt and braces: prove the protected wording really is gone from what we ship.
_FORBIDDEN = [
    ("BAARS", "Difficulty sustaining my attention in tasks or fun activities"),
    ("RCADS", "When I have a problem, I get a funny feeling in my stomach"),
    ("IES-R", "Any reminder brought back feelings about it"),
    ("Y-BOCS", "Time occupied by obsessive thoughts"),
    ("Y-BOCS checklist", "I am concerned or disgusted with bodily waste"),
    ("CY-BOCS checklist", "Fear harm will come to others"),
]


# ── Assemble ──────────────────────────────────────────────────────────────────
_rmet = image_map + '/* ── RMET images inlined above (single-file build only) ── */' if image_map else ''
js_bundle = '\n\n'.join(p for p in [
    _rmet,
    strip_file_header(config),
    strip_file_header(scoring),
    sdqnorms,
    strip_file_header(scrnorms),
    strip_file_header(registry_online),
    strip_file_header(cutmaster),
    strip_file_header(validate),
    strip_file_header(state),
    strip_file_header(app),
    strip_file_header(results),
    suite_js,
    online_boot,
] if p)

title = "Clinical Supplement Suite"
out = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
{css}
</style>
<style>
{suite_css}
</style>
</head>
<body>
{body}

<script>
{js_bundle}
</script>
</body>
</html>"""

# Leak check runs on the text BEFORE it is written, so a stripping regex that
# silently stops matching can never put protected item text on disk here.
_leaks = [name for name, probe in _FORBIDDEN if probe in out]
if _leaks:
    sys.exit(f"[ABORT] Protected item text reached the build: {', '.join(_leaks)}. "
             "Nothing written. Fix the strip step in build.py before publishing.")
for name, probe in _FORBIDDEN:
    if probe not in registry:
        raise ValueError(f"{name} canary string no longer present in registry.js; "
                         "the leak check is testing nothing. Update _FORBIDDEN.")

OUT.parent.mkdir(exist_ok=True)
OUT.write_text(out, encoding='utf-8')
(HERE / 'BUILT_FROM.txt').write_text(
    f"Built from assessment_suite_project commit {app_commit}"
    f"{' (with uncommitted changes)' if app_dirty else ''}\n", encoding='utf-8')
print(f"[OK] Built: {OUT}  ({OUT.stat().st_size / 1024:.0f} KB)")
print(f"     Copyright check passed ({len(_FORBIDDEN)} protected instruments absent)")
print(f"     Filtered to {len(ALLOW)} copyright-clean instruments")
if app_dirty:
    print("     WARNING: the app had uncommitted changes; don't publish this build.")
